

create sequence JPAEXAM_BATTALION_SEQ
			    INCREMENT BY 1
				START WITH 1
				MINVALUE 1
				MAXVALUE 100
				CYCLE		
				CACHE 10;


CREATE TABLE JPAEXAM_BATTALION(
  bID NUMBER(13),
  bNAME varchar2(255) NOT NULL UNIQUE,
  CONSTRAINT pk_battalion primary key (bID));


INSERT INTO JPAEXAM_BATTALION VALUES (1, 'Air-Cav');
INSERT INTO JPAEXAM_BATTALION VALUES (2, 'Infantry');



create sequence JPAEXAM_SOLDIER_SEQ
			    INCREMENT BY 1
				START WITH 200
				MINVALUE 200
				MAXVALUE 300
				CYCLE		
				CACHE 10;

CREATE TABLE JPAEXAM_SOLDIER(
  sID NUMBER(13),
  sNAME varchar2(255) NOT NULL,
  sRank varchar2(255) NOT NULL,
  fk_bID NUMBER(13),
  CONSTRAINT pk_soldier primary key (sID),
  CONSTRAINT fk_soldier FOREIGN KEY( fk_bID ) REFERENCES JPAEXAM_BATTALION (bID));
  
INSERT INTO JPAEXAM_SOLDIER VALUES (200, 'John Doe', 'Sergeant', 1);
INSERT INTO JPAEXAM_SOLDIER VALUES (201, 'Jane Doe', 'Private', 2);
INSERT INTO JPAEXAM_SOLDIER VALUES (202, 'James Smith', 'Private', 1);  
  

CREATE TABLE JPAEXAM_SERGEANT(
  sID NUMBER(13),
  pSgtNum NUMBER(6) NOT NULL,
  CONSTRAINT pk_sergeant primary key (sID),
  CONSTRAINT fk_sergeant FOREIGN KEY( sID ) REFERENCES JPAEXAM_SOLDIER (sID));
  
INSERT INTO JPAEXAM_SERGEANT VALUES (200, 999);  
  
  

CREATE TABLE JPAEXAM_PRIVATE(
  sID NUMBER(13),
  pUnitNum NUMBER(6) NOT NULL,
  CONSTRAINT pk_private primary key (sID),
  CONSTRAINT fk_private FOREIGN KEY( sID ) REFERENCES JPAEXAM_SOLDIER (sID));

INSERT INTO JPAEXAM_PRIVATE VALUES (201, 333);  
INSERT INTO JPAEXAM_PRIVATE VALUES (202, 333);  
